name: ml_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - matplotlib=3.1.3
  - jupyter
  - nb_conda
  - xgboost
  - tensorflow
  - seaborn
  - tqdm
  - lightgbm
